site:
  title: MuYe
  description: My personal blog and docs with GitHub Pages.
  keywords: gitsite, git, static web site, html, tech-blogs, personal blog, tech
  theme: default
  language: zh-CN
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  root-path: /MuYe
  # set cdn path:
  cdn-path: /static
  navigation:
    - title: 博客
      uri: /blogs/all/index.html
    - title: 面经
      uri: /books/interview/index.html
    - title: 资料URL
      uri: /pages/reference/index.html
      # external: true
  git:
    base-url: https://github.com/michaelliao/gitsite/blob/main/source
  contact:
    name: MuYe (董梁)
    github: https://github.com/RCliang/MuYe
    twitter: https://www.zhihu.com/people/ricodong
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: true
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: disqus
      name: gitsite
    analytics:
      provider: google
      gtag: G-5Z40K7NBL5

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
